### ISSUE TITLE
Could you share the list of remaining model ids for your experiments and the pre-processed ShapeNet models?

### ISSUE THREAD

**Issue by wangg12** [NVlabs/latentfusion#2]
Hi authors, very nice work! 
I used your preprocess script for the ShapeNetCore.v2 data. However, after filtering out the models which are > 50MB and > 10 components, I can only get < 20k models. It is much fewer than what you reported in the paper (about 30k). So I wonder if you could share your list of model ids used in your experiments and the preprocessed ShapeNet models?

**Comment by vtasStu** [comment]
Hello， I use blender to deal with  ShapeNetCore.v2 too. I use different version of Blender, and get different error.
Which version of Blender do you use, and how do you download and install Blender？
